#!/bin/bash
#
# Junegunn Choi (junegunn.c@gmail.com)
# 2012/08/21-

TEMPLATE_PATH=$(dirname $BASH_SOURCE)/__template__

if [ $# -ne 1 ]; then
  echo "usage: $0 <app name>"
  exit 1
fi

if [ -e $1 ]; then
  echo "$1 already exists."
  exit 1
fi

for cmd in jruby gem nohup; do
  if [ -z "`which $cmd`" ]; then
    echo "Cannot find '$cmd' executable."
    exit 1
  fi
done

NAME=`basename $1`
mkdir -p $1
cat $TEMPLATE_PATH/service | \
  sed "s#^JRUBY_HOME=#JRUBY_HOME=$(cd "$(dirname $(which jruby))"; cd ..; pwd)#" | \
  sed "s#^export GEM_HOME=#export GEM_HOME=$(jruby `which gem` environment gemhome)#" | \
  sed "s#^export GEM_PATH=#export GEM_PATH=$(jruby `which gem` environment gempath)#" > $1/$NAME
chmod +x $1/$NAME
cp $TEMPLATE_PATH/service.rb $1/$NAME.rb
cp $TEMPLATE_PATH/Gemfile* $1/
mkdir $1/log $1/pid

echo "$1 created!"
